# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kronFrame', '0011_auto_20151215_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prereq',
            field=models.ManyToManyField(to='kronFrame.Course'),
        ),
    ]
